// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ertoivqgzhgimdghtcxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVydG9pdnFnemhnaW1kZ2h0Y3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjM4MzQsImV4cCI6MjA3MTM5OTgzNH0.5O_koR60UckVBiow0MfWCvA7q30ilamxBxMwgxPWmY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});